"""ajout du champ auteur

Revision ID: 49cffa260a68
Revises: 2b2f63b3bbeb
Create Date: 2024-03-14 08:51:01.363160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cffa260a68'
down_revision: Union[str, None] = '2b2f63b3bbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taches', sa.Column('auteur', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_taches_auteur'), 'taches', ['auteur'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taches_auteur'), table_name='taches')
    op.drop_column('taches', 'auteur')
    # ### end Alembic commands ###
