"""definition du champ commentaire et date_fin dans les schemas comme  optionels

Revision ID: d18117ade4c9
Revises: 49cffa260a68
Create Date: 2024-03-14 18:51:09.002639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18117ade4c9'
down_revision: Union[str, None] = '49cffa260a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
